version: '3'

services:
    database:
        image: postgres
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=thepassword
            - POSTGRES_DB=mydb
        volumes:
            - mydbData:/var/lib/postgresql/data

volumes:
    mydbData:
        driver: local
